/**
 * Print a fresh VAPID key pair for Web Push.
 *
 * Run with: `pnpm push:keys` (or `tsx scripts/generate-vapid.ts`).
 * Copy the output into .env.local and restart the server.
 *
 * VAPID keys identify YOUR server to the push services run by browser
 * vendors (FCM for Chrome/Edge, Mozilla autopush for Firefox, Apple
 * for Safari). They never need to rotate unless leaked, and you only
 * need one pair per Potluck deployment.
 */
import webpush from "web-push";

const keys = webpush.generateVAPIDKeys();
const block = [
  "# Generated by scripts/generate-vapid.ts",
  `VAPID_PUBLIC_KEY="${keys.publicKey}"`,
  `VAPID_PRIVATE_KEY="${keys.privateKey}"`,
  `# VAPID_SUBJECT must be a contact mailto: or https: URL.`,
  `VAPID_SUBJECT="mailto:you@example.com"`,
].join("\n");

console.log(block);
